name = "life-in-the-uk-quiz"
main = "worker.js"
compatibility_date = "2026-02-22"
account_id = "5251d16ad29f52e5dfd79e2f20ece730"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "PROGRESS_KV"
id = "fefd2a8b71de492c8db5af9fa3aa9939"

[[d1_databases]]
binding = "DB"
database_name = "lifeuk-progress"
database_id = "2aa0433c-543d-48da-a026-bfc2419509ef"
